
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'and bool chaves_f chaves_i desligar dispositivo dois_pontos dot entao enviar_alerta igual ligar msg namedevice namesensor num observation oplogic para_todos parenteses_f parenteses_i se senao set virgula\n    PROGRAMM : DEVICES CMDS\n    \n    DEVICES : DEVICE DEVICES\n            | DEVICE\n    \n    DEVICE : dispositivo dois_pontos chaves_i namedevice chaves_f\n           | dispositivo dois_pontos chaves_i namedevice virgula observation chaves_f\n    \n    CMDS : CMD dot CMD\n         | CMD\n    \n    CMD : ATTRIB\n         | OBSACT\n         | ACT\n    \n    ATTRIB : set observation igual VAR\n    \n    OBSACT : SE\n           | SES\n    \n    SE : se OBS entao ACT\n    \n    SES : se OBS entao ACT senao ACT\n    \n    OBS : observation oplogic OBSL\n    \n    OBSL : VAR\n         | VAR and OBS\n    \n    VAR : num bool\n    \n    ACT : ACTION namedevice\n        | enviar_alerta parenteses_i msg parenteses_f namedevice\n        | enviar_alerta parenteses_i msg virgula observation parenteses_f namedevice\n    \n    ACTION : ligar\n           | desligar\n    '
    
_lr_action_items = {'dispositivo':([0,3,40,51,],[4,4,-4,-5,]),'$end':([1,5,6,7,8,9,11,12,22,27,33,37,42,43,49,52,],[0,-1,-7,-8,-9,-10,-12,-13,-20,-6,-11,-14,-19,-21,-15,-22,]),'set':([2,3,18,20,40,51,],[10,-3,-2,10,-4,-5,]),'enviar_alerta':([2,3,18,20,30,40,45,51,],[14,-3,-2,14,14,-4,14,-5,]),'se':([2,3,18,20,40,51,],[15,-3,-2,15,-4,-5,]),'ligar':([2,3,18,20,30,40,45,51,],[16,-3,-2,16,16,-4,16,-5,]),'desligar':([2,3,18,20,30,40,45,51,],[17,-3,-2,17,17,-4,17,-5,]),'dois_pontos':([4,],[19,]),'dot':([6,7,8,9,11,12,22,33,37,42,43,49,52,],[20,-8,-9,-10,-12,-13,-20,-11,-14,-19,-21,-15,-22,]),'observation':([10,15,36,41,46,],[21,25,44,47,25,]),'namedevice':([13,16,17,26,35,48,],[22,-23,-24,32,43,52,]),'parenteses_i':([14,],[23,]),'chaves_i':([19,],[26,]),'igual':([21,],[28,]),'senao':([22,37,43,52,],[-20,45,-21,-22,]),'msg':([23,],[29,]),'entao':([24,38,39,42,50,],[30,-16,-17,-19,-18,]),'oplogic':([25,],[31,]),'num':([28,31,],[34,34,]),'parenteses_f':([29,44,],[35,48,]),'virgula':([29,32,],[36,41,]),'chaves_f':([32,47,],[40,51,]),'bool':([34,],[42,]),'and':([39,42,],[46,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROGRAMM':([0,],[1,]),'DEVICES':([0,3,],[2,18,]),'DEVICE':([0,3,],[3,3,]),'CMDS':([2,],[5,]),'CMD':([2,20,],[6,27,]),'ATTRIB':([2,20,],[7,7,]),'OBSACT':([2,20,],[8,8,]),'ACT':([2,20,30,45,],[9,9,37,49,]),'SE':([2,20,],[11,11,]),'SES':([2,20,],[12,12,]),'ACTION':([2,20,30,45,],[13,13,13,13,]),'OBS':([15,46,],[24,50,]),'VAR':([28,31,],[33,39,]),'OBSL':([31,],[38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROGRAMM","S'",1,None,None,None),
  ('PROGRAMM -> DEVICES CMDS','PROGRAMM',2,'p_programm','parser.py',120),
  ('DEVICES -> DEVICE DEVICES','DEVICES',2,'p_devices','parser.py',126),
  ('DEVICES -> DEVICE','DEVICES',1,'p_devices','parser.py',127),
  ('DEVICE -> dispositivo dois_pontos chaves_i namedevice chaves_f','DEVICE',5,'p_device','parser.py',135),
  ('DEVICE -> dispositivo dois_pontos chaves_i namedevice virgula observation chaves_f','DEVICE',7,'p_device','parser.py',136),
  ('CMDS -> CMD dot CMD','CMDS',3,'p_cmds','parser.py',146),
  ('CMDS -> CMD','CMDS',1,'p_cmds','parser.py',147),
  ('CMD -> ATTRIB','CMD',1,'p_cmd','parser.py',156),
  ('CMD -> OBSACT','CMD',1,'p_cmd','parser.py',157),
  ('CMD -> ACT','CMD',1,'p_cmd','parser.py',158),
  ('ATTRIB -> set observation igual VAR','ATTRIB',4,'p_attrib','parser.py',164),
  ('OBSACT -> SE','OBSACT',1,'p_obsact','parser.py',170),
  ('OBSACT -> SES','OBSACT',1,'p_obsact','parser.py',171),
  ('SE -> se OBS entao ACT','SE',4,'p_se','parser.py',177),
  ('SES -> se OBS entao ACT senao ACT','SES',6,'p_ses','parser.py',183),
  ('OBS -> observation oplogic OBSL','OBS',3,'p_obs','parser.py',189),
  ('OBSL -> VAR','OBSL',1,'p_obsl','parser.py',195),
  ('OBSL -> VAR and OBS','OBSL',3,'p_obsl','parser.py',196),
  ('VAR -> num bool','VAR',2,'p_var','parser.py',205),
  ('ACT -> ACTION namedevice','ACT',2,'p_act','parser.py',211),
  ('ACT -> enviar_alerta parenteses_i msg parenteses_f namedevice','ACT',5,'p_act','parser.py',212),
  ('ACT -> enviar_alerta parenteses_i msg virgula observation parenteses_f namedevice','ACT',7,'p_act','parser.py',213),
  ('ACTION -> ligar','ACTION',1,'p_action','parser.py',225),
  ('ACTION -> desligar','ACTION',1,'p_action','parser.py',226),
]
